name: Integration

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: docker build -t tinygraph/tinygraph tinygraph

      - name: Sanitize
        run: |
          docker run -t --rm --pull never -v $(pwd)/tinygraph:/app tinygraph/tinygraph make -j8 sanitize
          docker run -t --rm --pull never -v $(pwd)/tinygraph:/app tinygraph/tinygraph ./tinygraph-tests
          docker run -t --rm --pull never -v $(pwd)/tinygraph:/app tinygraph/tinygraph make clean
          docker run -t --rm --pull never -v $(pwd)/tinygraph:/app tinygraph/tinygraph make -j8
          docker run -t --rm --pull never -v $(pwd)/tinygraph:/app tinygraph/tinygraph ./tinygraph-example
          docker run -t --rm --pull never -v $(pwd)/tinygraph:/app tinygraph/tinygraph make clean

      - name: Compile
        run: docker run -t --rm --pull never -v $(pwd)/tinygraph:/app tinygraph/tinygraph make -j8

      - name: Install
        run: docker run -t --rm --pull never -v $(pwd)/tinygraph:/app tinygraph/tinygraph make -j8 install PREFIX=/app

      - name: Test
        run: |
          docker run -t --rm --pull never -v $(pwd)/tinygraph:/app tinygraph/tinygraph make clean
          docker run -t --rm --pull never -v $(pwd)/tinygraph:/app tinygraph/tinygraph make -j8 tinygraph-tests tinygraph-example
          docker run -t --rm --pull never -v $(pwd)/tinygraph:/app tinygraph/tinygraph ./tinygraph-tests
          docker run -t --rm --pull never -v $(pwd)/tinygraph:/app tinygraph/tinygraph ./tinygraph-example
