name: Integration

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker build -t tinygraph/tinygraph tinygraph

      - name: Sanitize
        run: |
          docker run -t --rm --pull never --read-only -v $(pwd)/tinygraph:/app tinygraph/tinygraph env CFLAGS='-O0 -g -fsanitize=undefined,address -fno-omit-frame-pointer' LDLIBS='-lasan -lubsan' make
          docker run -t --rm --pull never --read-only -v $(pwd)/tinygraph:/app tinygraph/tinygraph ./tinygraph-tests
          docker run -t --rm --pull never --read-only -v $(pwd)/tinygraph:/app tinygraph/tinygraph ./tinygraph-example
          docker run -t --rm --pull never --read-only -v $(pwd)/tinygraph:/app tinygraph/tinygraph make clean

      - name: Compile
        run: docker run -t --rm --pull never --read-only -v $(pwd)/tinygraph:/app tinygraph/tinygraph make

      - name: Install
        run: docker run -t --rm --pull never --read-only -v $(pwd)/tinygraph:/app tinygraph/tinygraph make install PREFIX=/app

      - name: Test
        run: docker run -t --rm --pull never --read-only -v $(pwd)/tinygraph:/app tinygraph/tinygraph ./tinygraph-tests

      - name: Example
        run: docker run -t --rm --pull never --read-only -v $(pwd)/tinygraph:/app tinygraph/tinygraph ./tinygraph-example
