cc_library(
  name = "zigzag",

  srcs = ["zigzag.c"],
  hdrs = ["zigzag.h"],

  deps = ["//tinygraph/utils:utils"],
)

cc_test(
  name = "zigzag-test",

  srcs = ["zigzag-test.c"],

  deps = [":zigzag"],
)
